### ISSUE TITLE
Professor Satyam Mukherjee Blog 

### ISSUE THREAD

**Issue by rsundhar2002** [ironhacks/ironhacks-blog#11]
I have attached the blog below for Professor Satyam Mukherjee's award. If we can finalize and post the blog tonight that would be great.  

https://docs.google.com/document/d/1Nwc5RcgkXIf4q3dKDJjtk5SHU1G1sMD3VQdSQUFpZ4Y/edit

**Comment by jialincheoh** [comment]
https://www.markdownguide.org/getting-started/
