### ISSUE TITLE
[Marketing] Mailchimp Registration Emails

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/ironhacks-blog#17]
Summary:

This issue is dedicated to generating the mailing list for the current registered users and assigning them the proper tags.

Drive Location:
https://drive.google.com/drive/u/0/folders/11TuqI6s_mp6y21B02n9uGgjCxiTaqHKr

Tasks:

- [x] Export Data from Mailchimp and merge with Drive (Data/Registrations)
- [x] Add tags to the users

**Comment by aronlindberg** [comment]
This is now fixed
