### ISSUE TITLE
Style changes

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-blog#2]
## Discussion from meeting ##

- [ ] Update navigation bar and call it IronHacks Blog
- [x] Make black page background yellow if possible 
- [x] Add link to www.ironhacks.com very prominently at the top of the page (e.g. in the header or navigation bar)
- [x] Remove email opendigital@purdue.edu

**Comment by sbrunswi** [comment]
@charrismatic  - we had promised Marketing the link the page and the updates a few days ago  already and they are waiting. Please resolve this as soon as possible if you can. We need to recruit.

**Comment by charrismatic** [comment]
> Update navigation bar and call it IronHacks Blog

This is already resolved as of yesterday's meeting.
