### ISSUE TITLE
[Development] Blog System and Implementation

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/ironhacks-blog#5]
As per Prof. Brunswicker's request

1) learn gohugo.io, 2) understand how www.rcodi.org links to repo RCODI-blog, same for www.ironhacks.com and ironhacks-blog, 3) make a pull request of the repo locally 4) Complete tutorial on how to set-up a hugo site by next week

**Comment by harshpavuluri** [comment]
@rsundhar2002 You should be able to edit my previous comment. If not make another comment detailing what needs to be done. I'm told that Professor spoke to you about it. If you run into any trouble, just let me know!

**Comment by rsundhar2002** [comment]
We are proud to announce that our Dr.Sabine Brunswicker was a member of the RCHE. The RCHE is a Purdue based Organization focused on Healthcare engineering. The Organization serves as a center for innovation in the healthcare space with a  mission to “Pursue a proactive, patient-centered, and wellness-focused healthcare delivery system by conducting impactful research that leverages collaborative partnerships”. The RCODI is looking forward to collaborating with the RCHE and other members to make an impact in the healthcare space.
