### ISSUE TITLE
Github MLH Partnership

### ISSUE THREAD

**Issue by rsundhar2002** [ironhacks/ironhacks-blog#8]
Attended the office hours for insight on how to run our Hackathon and market better to get more participants. 

Need to Focus on Marketing and Outreach

Post Flyers around campus

Have attached noted from the meeting below
email potential professors and partners 

[Running Hackathon notes.pdf](https://github.com/ironhacks/ironhacks-blog/files/9530922/Running.Hackathon.notes.pdf)

**Comment by ManthanKeim** [comment]
Meeting notes with Shubham from MLH - 09/20/2022:

1. APAC Region - Shubham


They don't support hackathons more than 24 or 48 hour as most of the coaches work voluntarily and have full time job elsewhere.
